### PR TITLE
API 3.0.0

### PR DESCRIPTION
**Pull request by ghost**
#1 Not working

### CODE REVIEW

**Comment by Infernus102** [comment]
Even EssentialsPE haven't updated to API 3.0.0

**Comment by BlawoHD** [comment]
EssentialsPE funktioniert net für nicht. Es hat die api 3.0.0-ALPHA1 noch nicht

**Comment by ghost** [comment]
EssentialsPE has not been updated to API 3.0.0-ALPHA1

**Comment by Infernus102** [comment]
Yes because the API isn't fully out yet, if you wanna update go ahead and change the api in your plugin, i am not gonna merge it.

**Pull request closed without merging**
